import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { ThemeProvider } from "next-themes";

import "@/shared/styles/globals.css";
import { ToastRegistry } from "@/shared/ui/Toast";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ToastRegistry />
        </ThemeProvider>
      </body>
    </html>
  );
}
