/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auctions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 경매 다건 조회
     * @description 경매 리스트들을 조회합니다.
     */
    get: operations["readAuctionList"];
    put?: never;
    /**
     * 경매 생성
     * @description 새로운 경매를 생성합니다.
     */
    post: operations["createAuction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/{auctionId}/emojis/{emojiType}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 경매 이모지 전송
     * @description 특정 경매에 대해 판매자가 이모지를 전송합니다.
     */
    post: operations["sendEmoji"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/{auctionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 경매 상세 조회
     * @description 특정 경매의 상세 정보(상품 정보, 가격 정보, 상태 정보)를 조회합니다.
     */
    get: operations["getAuctionDetail"];
    put?: never;
    post?: never;
    /**
     * 경매 삭제
     * @description 경매를 삭제합니다.
     */
    delete: operations["deleteAuction"];
    options?: never;
    head?: never;
    /**
     * 경매 취소
     * @description 경매를 취소합니다.
     */
    patch: operations["cancelAuction"];
    trace?: never;
  };
  "/api/v1/users/{userid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 사용자 정보
     * @description 특정 사용자의 정보를 반환합니다.
     */
    get: operations["getUserInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tags/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 태그 자동 완성
     * @description 태그 검색 시 `자동 완성 검색어`를 5개 제공합니다.
     */
    get: operations["searchTag"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat-rooms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 채팅방 목록 조회
     * @description 로그인한 사용자의 채팅방 목록을 조회합니다.
     *     - scope=ALL: 전체 대화
     *     - scope=BUY: 구매자로 참여한 대화
     *     - scope=SELL: 판매자로 참여한 대화
     *     정렬: lastMessageAt 내림차순(최신순)
     *     unreadCount: 상대방이 보낸 메시지 중 읽지 않은 메시지 개수
     */
    get: operations["getChatRooms"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 로그인 URL 반환
     * @description provider에 맞는 로그인 url을 반환합니다.
     */
    get: operations["redirectToLogin"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/validate-tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 두 토큰 중 하나라도 사용 가능한가 true/false 반환
     * @description 쿠키 속 액세스 토큰과 리프레시 토큰 중 하나라도 사용 가능하면 true, 둘 다 만료되었으면 false 반환합니다.
     */
    get: operations["validateTokens"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/callback/naver": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 네이버 로그인 콜백 요청
     * @description 네이버로 로그인합니다.
     */
    get: operations["naverCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/callback/kakao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 카카오 로그인 콜백 요청
     * @description 카카오로 로그인합니다. 한번 회원가입된 아이디로 다시 이 테스트를 하시면 KOE320 오류가 뜹니다. 대신 2번째 로그인부턴 바로 성공 결과가 뜹니다.
     */
    get: operations["kakaoCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/callback/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 구글 로그인 콜백 요청
     * @description 구글로 로그인합니다.
     */
    get: operations["googleCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/basic": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 로그인 이후 유저 기본 정보 반환
     * @description 쿠키 속 액세스 토큰을 받고 해당 사용자에 맞는 이메일, 유저네임, 프로필url을 반환합니다.
     */
    get: operations["returnBasicUserInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/{auctionId}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 경매 가격 변동 내역 조회
     * @description 특정 경매의 가격 변동 내역을 조회합니다.
     */
    get: operations["getAuctionHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 경매 검색
     * @description 경매를 검색하여 조회합니다.
     */
    get: operations["searchAuction"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 경매 생성 요청 DTO */
    AuctionCreateRequest: {
      /**
       * Format: int64
       * @description 판매자 id
       * @example 1
       */
      sellerId: number;
      /**
       * @description 경매 제목
       * @example 테스트 제목
       */
      title: string;
      /**
       * @description 경매 설명
       * @example 테스트 설명
       */
      description: string;
      /**
       * @description 경매 카테고리
       * @example 1
       * @enum {string}
       */
      category:
        | "CLOTHING"
        | "GOODS"
        | "FURNITURE_INTERIOR"
        | "DIGITAL"
        | "APPLIANCE"
        | "SPORTS_LEISURE"
        | "PET"
        | "HOBBY"
        | "BOOK_TICKET"
        | "ETC";
      /**
       * @description 경매 태그
       * @example [
       *       {
       *         "name": "나이키"
       *       },
       *       {
       *         "name": "운동화"
       *       }
       *     ]
       */
      tags?: components["schemas"]["TagInfo"][];
      /**
       * Format: int64
       * @description 경매 시작가
       * @example 10000
       */
      startPrice: number;
      /**
       * Format: int64
       * @description 경매 스탑 로스
       * @example 9000
       */
      stopLoss: number;
      /**
       * Format: int64
       * @description 경매 하락 금액
       * @example 50
       */
      dropAmount: number;
      /**
       * Format: date-time
       * @description 경매 시작 시간
       */
      startAt: string;
    };
    /**
     * @description 태그 등록 요청 DTO
     * @example [
     *       {
     *         "name": "나이키"
     *       },
     *       {
     *         "name": "운동화"
     *       }
     *     ]
     */
    TagInfo: {
      /** @description 단일 경매 태그 */
      name: string;
    };
    ApiResponseAuctionCreateResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["AuctionCreateResponse"];
    };
    /** @description 경매 생성 응답 DTO */
    AuctionCreateResponse: {
      /**
       * Format: int64
       * @description 경매 id
       */
      auctionId?: number;
      /**
       * Format: int64
       * @description 판매자 id
       */
      sellerId?: number;
      /** @description 경매 제목 */
      title?: string;
      /** @description 경매 설명 */
      description?: string;
      /**
       * @description 경매 카테고리
       * @enum {string}
       */
      category?:
        | "CLOTHING"
        | "GOODS"
        | "FURNITURE_INTERIOR"
        | "DIGITAL"
        | "APPLIANCE"
        | "SPORTS_LEISURE"
        | "PET"
        | "HOBBY"
        | "BOOK_TICKET"
        | "ETC";
      tags?: string[];
      /**
       * Format: int64
       * @description 경매 시작가
       */
      startPrice?: number;
      /**
       * Format: int64
       * @description 경매 현재가
       */
      currentPrice?: number;
      /**
       * Format: int64
       * @description 경매 스탑 로스
       */
      stopLoss?: number;
      /**
       * Format: int64
       * @description 경매 하락 금액
       */
      dropAmount?: number;
      /**
       * @description 경매 상태
       * @enum {string}
       */
      status?: "SCHEDULED" | "PROCESS" | "COMPLETED" | "FAILED" | "CANCELED";
      /**
       * Format: date-time
       * @description 경매 시작 시간
       */
      startAt?: string;
    };
    ApiResponseVoid: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: Record<string, never>;
    };
    ApiResponseAuctionCancelResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["AuctionCancelResponse"];
    };
    AuctionCancelResponse: {
      /** Format: int64 */
      auctionId?: number;
      /** @enum {string} */
      status?: "SCHEDULED" | "PROCESS" | "COMPLETED" | "FAILED" | "CANCELED";
    };
    ApiResponseUserInfoResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["UserInfoResponse"];
    };
    UserInfoResponse: {
      /** @description 이 프로필이 본인인지 확인하는 필드 */
      isOwner?: boolean;
      /**
       * Format: int64
       * @description 유저 id
       */
      userid?: number;
      /** @description 유저 이름 */
      username?: string;
      /** @description 유저 이메일 */
      email?: string;
      /** @description 유저 프로필 이미지 url */
      profileImage?: string;
      /**
       * Format: int64
       * @description 이 사용자가 받은 총 리뷰
       */
      totalReviews?: number;
      /**
       * Format: double
       * @description 이 사용자의 평균 별점 (소수점)
       */
      rating?: number;
    };
    /** @description 태그 검색 요청 DTO */
    SearchTagRequest: {
      /**
       * @description 태그 검색어
       * @example 노트북
       */
      keyword?: string;
    };
    ApiResponseSearchTagResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["SearchTagResponse"];
    };
    /** @description 태그 검색 응답 DTO */
    SearchTagResponse: {
      /** @description 태그 자동 완성 */
      tags?: string[];
    };
    ApiResponseListChatRoomListResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["ChatRoomListResponse"][];
    };
    /** @description 경매 상품 정보 DTO */
    AuctionInfo: {
      /**
       * Format: int64
       * @description 경매 ID
       */
      auctionId?: number;
      /** @description 경매 상품명 */
      title?: string;
      /** @description 경매 대표 이미지 URL */
      imageUrl?: string;
    };
    /** @description 채팅방 목록 아이템 DTO */
    ChatRoomListResponse: {
      /**
       * Format: int64
       * @description 채팅방 ID
       */
      chatRoomId?: number;
      /**
       * Format: int64
       * @description 거래 ID
       */
      tradeId?: number;
      partner?: components["schemas"]["PartnerInfo"];
      auction?: components["schemas"]["AuctionInfo"];
      lastMessage?: components["schemas"]["LastMessageInfo"];
      /**
       * Format: int64
       * @description 읽지 않은 메시지 수
       */
      unreadCount?: number;
    };
    /** @description 마지막 메시지 정보 DTO */
    LastMessageInfo: {
      /**
       * Format: date-time
       * @description 마지막 메시지 시간
       */
      lastMessageAt?: string;
      /** @description 마지막 메시지 프리뷰 */
      preview?: string;
      /**
       * @description 마지막 메시지 타입
       * @enum {string}
       */
      type?: "TEXT" | "IMAGE" | "SYSTEM";
    };
    /** @description 상대방 정보 DTO */
    PartnerInfo: {
      /**
       * Format: int64
       * @description 상대방 ID
       */
      partnerId?: number;
      /** @description 상대방 닉네임 */
      username?: string;
      /** @description 상대방 프로필 이미지 URL */
      profileImageUrl?: string;
    };
    ApiResponseString: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: string;
    };
    ApiResponseBoolean: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: boolean;
    };
    ApiResponseLoginUserResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["LoginUserResponse"];
    };
    LoginUserResponse: {
      userEmail?: string;
      username?: string;
      userProfileUrl?: string;
    };
    ApplicationContext: {
      parent?: components["schemas"]["ApplicationContext"];
      id?: string;
      displayName?: string;
      autowireCapableBeanFactory?: components["schemas"]["AutowireCapableBeanFactory"];
      /** Format: int64 */
      startupDate?: number;
      applicationName?: string;
      environment?: components["schemas"]["Environment"];
      /** Format: int32 */
      beanDefinitionCount?: number;
      beanDefinitionNames?: string[];
      parentBeanFactory?: components["schemas"]["BeanFactory"];
      classLoader?: {
        name?: string;
        registeredAsParallelCapable?: boolean;
        parent?: {
          name?: string;
          registeredAsParallelCapable?: boolean;
          unnamedModule?: {
            name?: string;
            classLoader?: {
              name?: string;
              registeredAsParallelCapable?: boolean;
              definedPackages?: {
                name?: string;
                annotations?: Record<string, never>[];
                declaredAnnotations?: Record<string, never>[];
                sealed?: boolean;
                specificationTitle?: string;
                specificationVersion?: string;
                specificationVendor?: string;
                implementationTitle?: string;
                implementationVersion?: string;
                implementationVendor?: string;
              }[];
              defaultAssertionStatus?: boolean;
            };
            descriptor?: {
              open?: boolean;
              automatic?: boolean;
            };
            named?: boolean;
            annotations?: Record<string, never>[];
            declaredAnnotations?: Record<string, never>[];
            packages?: string[];
            nativeAccessEnabled?: boolean;
            layer?: Record<string, never>;
          };
          definedPackages?: {
            name?: string;
            annotations?: Record<string, never>[];
            declaredAnnotations?: Record<string, never>[];
            sealed?: boolean;
            specificationTitle?: string;
            specificationVersion?: string;
            specificationVendor?: string;
            implementationTitle?: string;
            implementationVersion?: string;
            implementationVendor?: string;
          }[];
          defaultAssertionStatus?: boolean;
        };
        unnamedModule?: {
          name?: string;
          classLoader?: {
            name?: string;
            registeredAsParallelCapable?: boolean;
            definedPackages?: {
              name?: string;
              annotations?: Record<string, never>[];
              declaredAnnotations?: Record<string, never>[];
              sealed?: boolean;
              specificationTitle?: string;
              specificationVersion?: string;
              specificationVendor?: string;
              implementationTitle?: string;
              implementationVersion?: string;
              implementationVendor?: string;
            }[];
            defaultAssertionStatus?: boolean;
          };
          descriptor?: {
            open?: boolean;
            automatic?: boolean;
          };
          named?: boolean;
          annotations?: Record<string, never>[];
          declaredAnnotations?: Record<string, never>[];
          packages?: string[];
          nativeAccessEnabled?: boolean;
          layer?: Record<string, never>;
        };
        definedPackages?: {
          name?: string;
          annotations?: Record<string, never>[];
          declaredAnnotations?: Record<string, never>[];
          sealed?: boolean;
          specificationTitle?: string;
          specificationVersion?: string;
          specificationVendor?: string;
          implementationTitle?: string;
          implementationVersion?: string;
          implementationVendor?: string;
        }[];
        defaultAssertionStatus?: boolean;
      };
    };
    AutowireCapableBeanFactory: Record<string, never>;
    BeanFactory: Record<string, never>;
    Environment: {
      activeProfiles?: string[];
      defaultProfiles?: string[];
    };
    FilterRegistration: {
      servletNameMappings?: string[];
      urlPatternMappings?: string[];
      name?: string;
      className?: string;
      initParameters?: Record<string, string>;
    };
    HttpStatusCode: {
      error?: boolean;
      is4xxClientError?: boolean;
      is5xxServerError?: boolean;
      is1xxInformational?: boolean;
      is2xxSuccessful?: boolean;
      is3xxRedirection?: boolean;
    };
    JspConfigDescriptor: {
      taglibs?: components["schemas"]["TaglibDescriptor"][];
      jspPropertyGroups?: components["schemas"]["JspPropertyGroupDescriptor"][];
    };
    JspPropertyGroupDescriptor: {
      buffer?: string;
      trimDirectiveWhitespaces?: string;
      errorOnUndeclaredNamespace?: string;
      deferredSyntaxAllowedAsLiteral?: string;
      elIgnored?: string;
      isXml?: string;
      urlPatterns?: string[];
      defaultContentType?: string;
      errorOnELNotFound?: string;
      pageEncoding?: string;
      scriptingInvalid?: string;
      includePreludes?: string[];
      includeCodas?: string[];
    };
    RedirectView: {
      applicationContext?: components["schemas"]["ApplicationContext"];
      servletContext?: components["schemas"]["ServletContext"];
      contentType?: string;
      requestContextAttribute?: string;
      staticAttributes?: Record<string, Record<string, never>>;
      exposePathVariables?: boolean;
      exposeContextBeansAsAttributes?: boolean;
      exposedContextBeanNames?: string[];
      beanName?: string;
      url?: string;
      contextRelative?: boolean;
      http10Compatible?: boolean;
      exposeModelAttributes?: boolean;
      encodingScheme?: string;
      statusCode?: components["schemas"]["HttpStatusCode"];
      expandUriTemplateVariables?: boolean;
      propagateQueryParams?: boolean;
      hosts?: string[];
      propagateQueryProperties?: boolean;
      redirectView?: boolean;
      attributes?: Record<string, string>;
      attributesMap?: Record<string, Record<string, never>>;
      attributesCSV?: string;
    };
    ServletContext: {
      classLoader?: {
        name?: string;
        registeredAsParallelCapable?: boolean;
        definedPackages?: {
          name?: string;
          annotations?: Record<string, never>[];
          declaredAnnotations?: Record<string, never>[];
          sealed?: boolean;
          specificationTitle?: string;
          specificationVersion?: string;
          specificationVendor?: string;
          implementationTitle?: string;
          implementationVersion?: string;
          implementationVendor?: string;
        }[];
        defaultAssertionStatus?: boolean;
      };
      /** Format: int32 */
      majorVersion?: number;
      /** Format: int32 */
      minorVersion?: number;
      /** Format: int32 */
      effectiveMajorVersion?: number;
      /** Format: int32 */
      effectiveMinorVersion?: number;
      servletRegistrations?: Record<string, components["schemas"]["ServletRegistration"]>;
      sessionTrackingModes?: ("COOKIE" | "URL" | "SSL")[];
      defaultSessionTrackingModes?: ("COOKIE" | "URL" | "SSL")[];
      requestCharacterEncoding?: string;
      responseCharacterEncoding?: string;
      effectiveSessionTrackingModes?: ("COOKIE" | "URL" | "SSL")[];
      serverInfo?: string;
      contextPath?: string;
      attributeNames?: Record<string, never>;
      initParameterNames?: Record<string, never>;
      servletContextName?: string;
      filterRegistrations?: Record<string, components["schemas"]["FilterRegistration"]>;
      sessionCookieConfig?: components["schemas"]["SessionCookieConfig"];
      jspConfigDescriptor?: components["schemas"]["JspConfigDescriptor"];
      virtualServerName?: string;
      /** Format: int32 */
      sessionTimeout?: number;
    };
    ServletRegistration: {
      mappings?: string[];
      runAsRole?: string;
      name?: string;
      className?: string;
      initParameters?: Record<string, string>;
    };
    SessionCookieConfig: {
      /** Format: int32 */
      maxAge?: number;
      domain?: string;
      name?: string;
      path?: string;
      attributes?: Record<string, string>;
      /** @deprecated */
      comment?: string;
      secure?: boolean;
      httpOnly?: boolean;
    };
    TaglibDescriptor: {
      taglibURI?: string;
      taglibLocation?: string;
    };
    ApiResponseAuctionListReadResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["AuctionListReadResponse"];
    };
    /** @description 메인 응답 DTO */
    AuctionListReadResponse: {
      /**
       * Format: date-time
       * @description 실시간 인기 랭킹 목록
       */
      serverAt?: string;
      /** @description 실시간 인기 랭킹 목록 */
      popularList?: components["schemas"]["PopularInfo"][];
      /** @description 경매 진행 중 목록 */
      processList?: components["schemas"]["ProcessInfo"][];
      /** @description 경매 예정 목록 */
      scheduledList?: components["schemas"]["ScheduledInfo"][];
    };
    /** @description 실시간 인기 랭킹 응답 DTO */
    PopularInfo: {
      /**
       * Format: int64
       * @description 경매 ID
       */
      auctionId?: number;
      /** @description 상품 이미지 URL */
      imageUrl?: string;
      /** @description 상품 제목 */
      title?: string;
      /**
       * Format: int64
       * @description 시작가
       */
      startPrice?: number;
      /**
       * Format: int64
       * @description 현재가
       */
      currentPrice?: number;
      /**
       * Format: int64
       * @description 하락 퍼센트
       */
      discountRate?: number;
      /** @description 사용자 찜 여부 */
      isLiked?: boolean;
      /**
       * Format: date-time
       * @description 경매 시작 시간
       */
      startedAt?: string;
    };
    /** @description 경매 진행 중 응답 DTO */
    ProcessInfo: {
      /**
       * Format: int64
       * @description 경매 ID
       */
      auctionId?: number;
      /** @description 상품 이미지 URL 목록 */
      imageUrl?: string;
      /** @description 상품 제목 */
      title?: string;
      /**
       * Format: int64
       * @description 시작가
       */
      startPrice?: number;
      /**
       * Format: int64
       * @description 현재가
       */
      currentPrice?: number;
      /**
       * Format: int64
       * @description 하락 퍼센트
       */
      discountRate?: number;
      /** @description 사용자 찜 여부 */
      isLiked?: boolean;
      /**
       * Format: date-time
       * @description 경매 시작 시간
       */
      startedAt?: string;
    };
    /** @description 경매 예정 응답 DTO */
    ScheduledInfo: {
      /**
       * Format: int64
       * @description 경매 ID
       */
      auctionId?: number;
      /** @description 상품 이미지 URL 목록 */
      imageUrl?: string;
      /** @description 상품 제목 */
      title?: string;
      /**
       * Format: int64
       * @description 시작가
       */
      startPrice?: number;
      /** @description 사용자 찜 여부 */
      isLiked?: boolean;
      /**
       * Format: date-time
       * @description 경매 시작 시간
       */
      startedAt?: string;
    };
    ApiResponseAuctionDetailResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["AuctionDetailResponse"];
    };
    /** @description 경매 상세 응답 DTO */
    AuctionDetailResponse: {
      /**
       * Format: int64
       * @description 경매 ID
       */
      auctionId?: number;
      /** @description 상품 제목 */
      title?: string;
      /** @description 상품 설명 */
      description?: string;
      /**
       * @description 카테고리
       * @enum {string}
       */
      category?:
        | "CLOTHING"
        | "GOODS"
        | "FURNITURE_INTERIOR"
        | "DIGITAL"
        | "APPLIANCE"
        | "SPORTS_LEISURE"
        | "PET"
        | "HOBBY"
        | "BOOK_TICKET"
        | "ETC";
      /** @description 상품 이미지 URL 목록 */
      imageUrls?: string[];
      seller?: components["schemas"]["SellerInfo"];
      /**
       * Format: int64
       * @description 시작가
       */
      startPrice?: number;
      /**
       * Format: int64
       * @description 현재가 (예정 : 시작가)
       */
      currentPrice?: number;
      /**
       * Format: int64
       * @description 최소 보장가 (판매자만)
       */
      stopLoss?: number;
      /**
       * Format: double
       * @description 하락 퍼센트 (예정 : null)
       */
      discountRate?: number;
      /**
       * @description 경매 상태
       * @enum {string}
       */
      status?: "SCHEDULED" | "PROCESS" | "COMPLETED" | "FAILED" | "CANCELED";
      /**
       * Format: int64
       * @description 찜 수
       */
      likeCount?: number;
      /** @description 사용자 찜 여부 */
      isLiked?: boolean;
      /**
       * Format: int64
       * @description 실시간 접속자 수
       */
      viewerCount?: number;
      /**
       * Format: date-time
       * @description 경매 시작 시간
       */
      startedAt?: string;
      /** @description 최근 가격 하락 내역 */
      recentPriceHistory?: components["schemas"]["AuctionHistoryResponse"][];
      /** @description 태그 목록 */
      tags?: string[];
    };
    /** @description 경매 가격 변동 내역 응답 DTO */
    AuctionHistoryResponse: {
      /**
       * Format: int64
       * @description 가격 변동 내역 ID
       */
      historyId?: number;
      /**
       * Format: int64
       * @description 변경된 가격
       */
      currentPrice?: number;
      /**
       * Format: int64
       * @description 시점 접속자 수
       */
      viewerCount?: number;
      /**
       * Format: date-time
       * @description 가격 변동 시점
       */
      createdAt?: string;
    };
    /** @description 판매자 정보 응답 DTO */
    SellerInfo: {
      /**
       * Format: int64
       * @description 판매자 ID
       */
      sellerId?: number;
      /** @description 판매자 닉네임 */
      nickname?: string;
      /** @description 판매자 프로필 이미지 URL */
      profileImageUrl?: string;
      /**
       * Format: double
       * @description 판매자 평점
       */
      rating?: number;
      /**
       * Format: int64
       * @description 판매자 리뷰 수
       */
      reviewCount?: number;
    };
    ApiResponseAuctionHistoryResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["AuctionHistoryResponse"];
    };
    ApiResponseSliceResponseAuctionSearchResponse: {
      /** Format: int32 */
      code?: number;
      /** @enum {string} */
      status?:
        | "100 CONTINUE"
        | "101 SWITCHING_PROTOCOLS"
        | "102 PROCESSING"
        | "103 EARLY_HINTS"
        | "103 CHECKPOINT"
        | "200 OK"
        | "201 CREATED"
        | "202 ACCEPTED"
        | "203 NON_AUTHORITATIVE_INFORMATION"
        | "204 NO_CONTENT"
        | "205 RESET_CONTENT"
        | "206 PARTIAL_CONTENT"
        | "207 MULTI_STATUS"
        | "208 ALREADY_REPORTED"
        | "226 IM_USED"
        | "300 MULTIPLE_CHOICES"
        | "301 MOVED_PERMANENTLY"
        | "302 FOUND"
        | "302 MOVED_TEMPORARILY"
        | "303 SEE_OTHER"
        | "304 NOT_MODIFIED"
        | "305 USE_PROXY"
        | "307 TEMPORARY_REDIRECT"
        | "308 PERMANENT_REDIRECT"
        | "400 BAD_REQUEST"
        | "401 UNAUTHORIZED"
        | "402 PAYMENT_REQUIRED"
        | "403 FORBIDDEN"
        | "404 NOT_FOUND"
        | "405 METHOD_NOT_ALLOWED"
        | "406 NOT_ACCEPTABLE"
        | "407 PROXY_AUTHENTICATION_REQUIRED"
        | "408 REQUEST_TIMEOUT"
        | "409 CONFLICT"
        | "410 GONE"
        | "411 LENGTH_REQUIRED"
        | "412 PRECONDITION_FAILED"
        | "413 PAYLOAD_TOO_LARGE"
        | "413 REQUEST_ENTITY_TOO_LARGE"
        | "414 URI_TOO_LONG"
        | "414 REQUEST_URI_TOO_LONG"
        | "415 UNSUPPORTED_MEDIA_TYPE"
        | "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        | "417 EXPECTATION_FAILED"
        | "418 I_AM_A_TEAPOT"
        | "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        | "420 METHOD_FAILURE"
        | "421 DESTINATION_LOCKED"
        | "422 UNPROCESSABLE_ENTITY"
        | "423 LOCKED"
        | "424 FAILED_DEPENDENCY"
        | "425 TOO_EARLY"
        | "426 UPGRADE_REQUIRED"
        | "428 PRECONDITION_REQUIRED"
        | "429 TOO_MANY_REQUESTS"
        | "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        | "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        | "500 INTERNAL_SERVER_ERROR"
        | "501 NOT_IMPLEMENTED"
        | "502 BAD_GATEWAY"
        | "503 SERVICE_UNAVAILABLE"
        | "504 GATEWAY_TIMEOUT"
        | "505 HTTP_VERSION_NOT_SUPPORTED"
        | "506 VARIANT_ALSO_NEGOTIATES"
        | "507 INSUFFICIENT_STORAGE"
        | "508 LOOP_DETECTED"
        | "509 BANDWIDTH_LIMIT_EXCEEDED"
        | "510 NOT_EXTENDED"
        | "511 NETWORK_AUTHENTICATION_REQUIRED";
      message?: string;
      data?: components["schemas"]["SliceResponseAuctionSearchResponse"];
    };
    /** @description 경매 검색 응답 DTO */
    AuctionSearchResponse: {
      /**
       * Format: int64
       * @description 경매 ID
       */
      auctionId?: number;
      /** @description 경매 이미지(썸네일) */
      imageUrl?: string;
      /** @description 경매 제목 */
      title?: string;
      /**
       * Format: int64
       * @description 경매 시작가
       */
      startPrice?: number;
      /**
       * Format: int64
       * @description 경매 현재가
       */
      currentPrice?: number;
      /**
       * Format: int64
       * @description 경매 하락율
       */
      discountRate?: number;
      /** @description 경매 찜 여부 */
      isLiked?: boolean;
      /**
       * Format: date-time
       * @description 경매 시작일
       */
      startedAt?: string;
      /**
       * @description 경매 상태 (경매 예정, 경매 진행 중, 경매 종료)
       * @enum {string}
       */
      status?: "SCHEDULED" | "PROCESS" | "COMPLETED" | "FAILED" | "CANCELED";
    };
    SliceResponseAuctionSearchResponse: {
      slice?: components["schemas"]["AuctionSearchResponse"][];
      hasNext?: boolean;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: date-time */
      timeStamp?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  readAuctionList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseAuctionListReadResponse"];
        };
      };
    };
  };
  createAuction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuctionCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseAuctionCreateResponse"];
        };
      };
      "400 BAD_REQUEST": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  sendEmoji: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 경매 ID
         * @example 1
         */
        auctionId: number;
        /**
         * @description 이모지 타입
         * @example LIKE
         */
        emojiType: "LIKE" | "FIRE" | "SAD" | "SMILE";
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseVoid"];
        };
      };
      "403 FORBIDDEN": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      "404 NOT_FOUND": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      "400 BAD_REQUEST": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getAuctionDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 경매 ID
         * @example 1
         */
        auctionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseAuctionDetailResponse"];
        };
      };
      "404 NOT_FOUND": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  deleteAuction: {
    parameters: {
      query: {
        /**
         * @description 사용자 ID
         * @example 1
         */
        userId: number;
      };
      header?: never;
      path: {
        /**
         * @description 경매 ID
         * @example 1
         */
        auctionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseVoid"];
        };
      };
      "403 FORBIDDEN": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      "404 NOT_FOUND": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      "409 CONFLICT": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  cancelAuction: {
    parameters: {
      query: {
        /**
         * @description 사용자 ID
         * @example 1
         */
        userId: number;
      };
      header?: never;
      path: {
        /**
         * @description 경매 ID
         * @example 1
         */
        auctionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseAuctionCancelResponse"];
        };
      };
      "403 FORBIDDEN": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      "404 NOT_FOUND": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
      "409 CONFLICT": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getUserInfo: {
    parameters: {
      query?: {
        loginId?: number;
      };
      header?: never;
      path: {
        userid: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseUserInfoResponse"];
        };
      };
    };
  };
  searchTag: {
    parameters: {
      query: {
        keyword: components["schemas"]["SearchTagRequest"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseSearchTagResponse"];
        };
      };
    };
  };
  getChatRooms: {
    parameters: {
      query?: {
        /**
         * @description 필터 범위 (ALL/BUY/SELL)
         * @example ALL
         */
        scope?: "ALL" | "BUY" | "SELL";
        /**
         * @description 사용자 ID(임시, 로그인 붙이면 제거 예정)
         * @example 1
         */
        userId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseListChatRoomListResponse"];
        };
      };
    };
  };
  redirectToLogin: {
    parameters: {
      query: {
        provider: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseString"];
        };
      };
    };
  };
  validateTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie: {
        accessToken: string;
        refreshToken: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  naverCallback: {
    parameters: {
      query: {
        code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseLoginUserResponse"];
        };
      };
    };
  };
  kakaoCallback: {
    parameters: {
      query: {
        code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["RedirectView"];
        };
      };
    };
  };
  googleCallback: {
    parameters: {
      query: {
        code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseLoginUserResponse"];
        };
      };
    };
  };
  returnBasicUserInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie: {
        accessToken: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseLoginUserResponse"];
        };
      };
    };
  };
  getAuctionHistory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 경매 ID
         * @example 1
         */
        auctionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseAuctionHistoryResponse"];
        };
      };
      "404 NOT_FOUND": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  searchAuction: {
    parameters: {
      query: {
        /**
         * @description 경매 검색어
         * @example 테스트
         */
        query?: string;
        /**
         * @description 경매 카테고리
         * @example DIGITAL
         */
        category?:
          | "CLOTHING"
          | "GOODS"
          | "FURNITURE_INTERIOR"
          | "DIGITAL"
          | "APPLIANCE"
          | "SPORTS_LEISURE"
          | "PET"
          | "HOBBY"
          | "BOOK_TICKET"
          | "ETC";
        /**
         * @description 경매 상태
         * @example SCHEDULED
         */
        status?: "SCHEDULED" | "PROCESS" | "COMPLETED" | "FAILED" | "CANCELED";
        /**
         * @description 최소가
         * @example 100
         */
        minPrice?: number;
        /**
         * @description 최고가
         * @example 1000000
         */
        maxPrice?: number;
        /**
         * @description 현재 페이지
         * @example 1
         */
        page: number;
        /**
         * @description 한 페이지 사이즈
         * @example 15
         */
        size?: number;
        /**
         * @description 정렬받는 내용
         * @example startedAt
         */
        sortBy?: string;
        /**
         * @description 정렬 차림
         * @example ASC
         */
        sortDirection?: "ASC" | "DESC";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>;
        content: {
          "application/json": components["schemas"]["ApiResponseSliceResponseAuctionSearchResponse"];
        };
      };
      "400 BAD_REQUEST": {
        headers: Record<string, unknown>;
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
